{
 "title": "Network and system performance",
 "description": "System metrics using Prometheus and Grafana",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Read and Write syscalls (Host)",
   "type": "timeseries",
   "description": "read and write system calls filtered",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ebpf_exporter_syscalls_total{syscall=\"read\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ebpf_exporter_syscalls_total{syscall=\"write\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Host Syscalls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_syscalls_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage percentage",
   "type": "timeseries",
   "description": "This query calculates the rate of change of the node_cpu_seconds_total metric in \"idle\" mode over the last 5 minutes, averages it over all instances, multiplies it by 100 to get a percentage, and then subtracts that from 100 to get the percentage of time spent not idle, i.e., the CPU utilization.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Available Memory",
   "type": "stat",
   "description": "Total available memory on the host",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Grafana CPU usage",
   "type": "timeseries",
   "description": "Grafana container cpu usage rate over last 5 mins",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 8 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service=\"grafana\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache miss",
   "type": "timeseries",
   "description": "Okay hear me out. When I checked all the available metrics provided by ebpf exporter there was no ebpf_exporter_llc_misses_total. So instead I added the metric ebpf_exporter_page_ops_total with the operation filter as add_to_page_cache_lur. Now the thing is in most cases *When the cache is fill* an LRU operation is a consequence of a cache miss so we can safely assume that a cache miss has happened and thus the LRU operation took place. However it is only true when the cache is full, so for an empty (or rather not full) cache even if there is a cache miss, an LRU operation will not take place and it will be undetected by this metric. Keeping in mind that the only reason that I added this in place of actual cache miss metric is due to the unavailability of the metric.",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_page_cache_ops_total{op=\"add_to_page_cache_lru\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage Prometheus",
   "type": "timeseries",
   "description": "CPU usage rate over last 5 minutes",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 15 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service=\"prometheus\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory available",
   "type": "timeseries",
   "description": "Memory available on host",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Network Traffic Down (Prometheus)",
   "type": "timeseries",
   "description": "Rate of downlink data over last 1 minutes in the Prometheus container",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{container_label_com_docker_compose_service=\"prometheus\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Traffic Up (Prometheus)",
   "type": "timeseries",
   "description": "Rate of uplink data over last 1 minutes in the Prometheus container",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{container_label_com_docker_compose_service=\"prometheus\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage Grafana",
   "type": "timeseries",
   "description": "We also added a threshold line to about 120% of the peak memory usage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_compose_service=\"grafana\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "90th percentile disk write latency in seconds",
   "type": "heatmap",
   "description": "This query calculates the rate of the ebpf_exporter_bio_latency_seconds_bucket metric in \"write\" mode over the last 1 minutes, sums it up by the le label (which represents the upper bound of each histogram bucket), and then calculates the 90th percentile of the resulting histogram.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(ebpf_exporter_bio_latency_seconds_bucket{operation=\"write\"}[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95th percentile of successful HTTP request latencies",
   "type": "timeseries",
   "description": "95th percentile latency of successful HTTP request to grafana",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(grafana_http_request_duration_seconds_bucket{status_code=\"200\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}