version: '3.1'

services:

  ebpf-exporter:
    image: ebpf_exporter:latest

    volumes:
      - /lib/modules:/lib/modules:ro
      - /sys:/sys:ro
      - /usr/src:/usr/src:ro
      - ./exporters/ebpf_exporter/examples:/examples
    privileged: true

    command:
      - '--config.dir=/examples'
      - '--config.names=syscalls,cachestat,cgroup,biolatency,icmp-ip,llcstat,percpu-softirq'
      - '--web.listen-address=0.0.0.0:9440'
    restart: "no"

    # Expose this container's port 9440 on port 9440
    ports:
      - 9440:9440

    container_name: my-ebpf-exporter

  node-exporter:
    image: prom/node-exporter

    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--web.listen-address=0.0.0.0:9441'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"

    restart: "no"
    cap_add:
    - SYS_TIME

    # Expose this container's port 9441 on port 9441
    ports:
      - 9441:9441


    container_name: my-node-exporter

  cadvisor:
    # image: gcr.io/cadvisor/cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.45.0
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro
      - /sys:/sys:ro

    devices:
      - /dev/kmsg
    command:
      - '--port=9442'
      - '-listen_ip=0.0.0.0'
    environment:
        - PORT=9442
    privileged: true
    restart: "no"

    ports:
      - 9442:9442

    container_name: my-cadvisor


  grafana:
    image: grafana/grafana-oss:9.4.7

    volumes:
      - ./grafana/data:/var/lib/grafana/
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    env_file:
      - ./grafana/config.monitoring

    # Do not change this
    user: "${CURRENT_UID}"

    restart: "unless-stopped"

    # Ensure that this service start only after prometheus
    depends_on:
      - prometheus
    # Expose this container's port 9091 on port 9091
    ports:
      - 9091:9091
    # Assign a meaningful name to this service using 'container_name'
    container_name: my-grafana
    # Allow this container to use at most two cores
    # Allow this container to use about 20% more of peak memory usage detected
    # Peak memory usage detected was about 124 mb
    deploy:
      resources:
        limits:
          cpus: '2'   
          memory: '150M'  # Limit to 256 megabytes of memory
        # reservations:
        #   cpus: '0.25'  # Reserve 25% of one CPU core
        #   memory: '128M'  # Reserve 128 megabytes of memory



  prometheus:
    image: prom/prometheus:v2.43.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./prometheus/storage/:/prometheus/
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

    # Do not change this
    user: "${CURRENT_UID}"
    restart: "no"

    # Ensure that this service start only after cadvisor, node-exporter, and ebpf-exporter
    depends_on:
      - cadvisor
      - node-exporter
      - ebpf-exporter
    # Expose this container's port 9090 on port 9090
    ports:
      - 9090:9090
    # Assign a meaningful name to this service using 'container_name'
    container_name: my-prometheus


