global:
  scrape_interval: 1s # By default, scrape targets every 15 seconds.

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "targets"

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 1s

    # Sources for data
    # You need to add the three services here. Use the container names and ports defined in the docker compose file.
    # Format 'name:port', ...
    static_configs:
      - targets:
          [
            my-ebpf-exporter:9440,
            my-node-exporter:9441,
            my-cadvisor:9442,
            my-grafana:9091,
            prometheus:9090,
          ]
